name: CI-Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: look for gcc11
      run: ls /usr/bin | grep gcc

    - name: install gcc 11
      run: |
        sudo apt update
        sudo apt install -y gcc-11 g++-11
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110

    - name: check compiler version
      run: gcc --version

    - name: trigger cmake
      run: |
        cmake . -B build
        cmake --build ./build -j8
    - name: run tests
      run: |
        cd ./build
        ctest -j8
