name: Proxy-Release

on:
  # run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number, e.g., 1.2.3'
        required: true
        default: '0.0.0'

jobs:
  release:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: release-drafter/release-drafter@v5
      name: create release draft
      id: release_draft
      
    - name: create zip archive
      run: Compress-Archive -Path '${{ github.GITHUB_WORKSPACE }}/proxy.h' -DestinationPath '${{ github.GITHUB_WORKSPACE }}/archive.zip'
      
    - name: upload artifacts
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release-draft.outputs.upload_url }}
        asset_path: ${{ github.GITHUB_WORKSPACE }}
        asset_name: archive.zip
        asset_content_type: application/zip
